### ISSUE TITLE
Allow string-multiplication

### ISSUE THREAD

**Issue by skx** [skx/gobasic#113]
I saw a bug report in a related project, relating to "string multiplication":

* https://github.com/richpl/PyBasic/issues/49

Supporting this would be nice and simple, and I recall it was always useful in Perl.

Something like the following should work as expected:

```BASIC
10 LET a = "STEVE "
20 LET b = 4
40 LET c = a * b
50 PRINT c
```

**Comment by prologic** [comment]
Hahahaha 😂 Does anyone seriously actually still write in BASIC? 🤔 Still a good idea to add this, if I recall this was alwaysupport by even GWBASIC IIRC 👌

**Comment by ThomasMertes** [comment]
I brought up the issue in [PyBasic](https://github.com/richpl/PyBasic/issues/49), because I thought that they introduced something that was not present in historic / vintage BASIC interpreters.
I was not able to find any reference in the manuals of GW-Basic, QuickBasic, QBasic or TI-99 extended Basic. At Rosetta Code the page about [repeating a string](https://rosettacode.org/wiki/Repeat_a_string) showed also no reference to a BASIC that supported string multiplication.
A reference to the manual of APC Megabasic ([link](https://manualzz.com/doc/33675672/megabasic-language-reference-and-programmer-s), see page 123) convinced me that at least some historic / vintage  BASIC had support for it.
So for me it is not about "it would be nice" or "it is useful in any other language". I think that interpreters for historic / vintage programming languages should refuse to introduce new features that were not present in the past (at historic / vintage time).
That said I am convinced and already added this feature to [Bas7](http://seed7.sourceforge.net/scrshots/bas7.htm), which is my interpreter of old BASIC programs. Btw: Bas7 is also at GitHub as part of [Seed7](http://seed7.sourceforge.net) project. See: [here](https://github.com/ThomasMertes/seed7/blob/master/prg/bas7.sd7)

**Comment by prologic** [comment]
Oh actually that's pretty cool! 👌 Maybe I can show this to my daughter and teach her to code 🤣
