### ISSUE TITLE
LET should be optional

### ISSUE THREAD

**Issue by udhos** [skx/gobasic#80]
I think LET should be optional.

```
$ more let.bas 
10 let a=1 : print a
20 b=2 : print b
$ 
$ gobasic let.bas 
1Error running program:
	Line 20 : Object{Type:error, Value:The variable 'b' doesn't exist}
$ 
```

**Comment by skx** [comment]
I can appreciate this is one that might surprise people, because there are several approaches various BASC inplementions have taken:

* Require the use of LET at all times.
  * The ZX Spectrum did that.
* Allow it, optionally.
  * e.g. "LET a = 3; b = 3"
* Require it when a variable is created, but not when it is updated:`
  * e.g. `LET a = 3;  a = 6;`

I think this would be a big change and would not be something I would implement.  This approach does require more typing, but it grants the ability to recognize invalid variables very easily.

**Comment by skx** [comment]
One thing that jumps out there is:

       210 IF D=2 THEN 260

That's something that is also not supported, since I'd need it to be written:

       210 IF D=2 THEN GOTO 260

I'll think about it some more, in the meantime I would be happy to accept a patch - though I suspect that's unlikely.

**Comment by udhos** [comment]
Yeah, supporting the short form "THEN line-number" would be nice too.
Filled https://github.com/skx/gobasic/issues/82

**Comment by skx** [comment]
I've been persuaded; I'll resolve this.

Not sure if I can add a rewrite at load-time, or if it needs real-handling.  I'll find out :)
